modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="ultimategearport"
version="1.0"
displayName="Ultimate Gear Port"
credits=""
authors="IceCubes"
description='''
This is a port of the Ultimate Gear from orespawn
'''

[[dependencies.ultimategearport]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.ultimategearport]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
